#!/bin/bash
# General bash setup for command-subcommand autocomplete.
# This will also add the main command to your $PATH.
# Source this file from your .profile or .bashrc to make permanent.
## e.g., `source ~/path/to/THISFILE.completion`

EXEDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export PATH="$PATH:$EXEDIR"
BINDIR=$EXEDIR'/bin/'


seqDB_toolsSubcmds=`find $BINDIR -maxdepth 1 -regex '.+.p[ly]' | perl -pe 's/.+\///g;s/\.[^.]+$/\n/'`
seqDB_toolsSubcmdsPerl=`find $BINDIR -maxdepth 1 -name '*.pl' | perl -pe 's/.+\///g;s/\.[^.]+$/\n/'`


_seqDB_tools ()
{
  local fileNames dirNames cur prev

  cur=${COMP_WORDS[COMP_CWORD]}
  prev1=${COMP_WORDS[COMP_CWORD-1]}
  prev2=${COMP_WORDS[COMP_CWORD-2]}

  COMPREPLY=()

  fileNames=''
  dirNames=''

  if [[ ${cur} == * && ${prev1} == *seqDB_tools ]]; then
      COMPREPLY=( $( compgen -W '$seqDB_toolsSubcmds' ${cur} ) )

  elif [[ ${cur} == * && ${prev1} == *-p* && ${prev2} == *seqDB_tools ]]; then
      COMPREPLY=( $( compgen -W '$seqDB_toolsSubcmdsPerl' ${cur} ) )
     
  else
      # no hiddne files/directories
      fileNames=$( compgen -f -X '.*' -- "$cur" )
      dirNames=$( compgen -d -X '.*' -- "$cur" )

      COMPREPLY=(
          $( compgen -W "$fileNames $dirNames" -- ${cur} )
      )
  fi

}

complete -o default -F _seqDB_tools seqDB_tools
